services:
  backend:
    build: ./back
    volumes:
      - ./sqlite_db:/app/sqlite_db
    expose:
      - "5000"
    networks:
      - mr_net

  frontend:
    build: ./front
    ports:
      - "80:80"
    networks:
      - mr_net


networks:
  mr_net: